# training data clean

In [1]:
import pandas as pd
import numpy as np
from numpy import savetxt
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
import sys
# np.set_printoptions(threshold=sys.maxsize)
import os
import matplotlib.pyplot as plt
from sklearn import datasets
import us as usStates

In [2]:
from datetime import datetime

def days(d1, d2):
    d1 = datetime.strptime(d1, "%m/%d/%Y")
    d2 = datetime.strptime(d2, "%m/%d/%Y")
    return abs((d2 - d1).days)+1

In [3]:
# from datetime import datetime

def weeks(d1, d2):
    d1 = datetime.strptime(d1, "%m/%d/%Y")
    d2 = datetime.strptime(d2, "%m/%d/%Y")
    return (abs((d2 - d1).days)+1)//7

In [4]:
def shuffle_in_unison(a, b):
    assert len(a) == len(b)
    shuffled_a = np.empty(a.shape, dtype=a.dtype)
    shuffled_b = np.empty(b.shape, dtype=b.dtype)
    permutation = np.random.permutation(len(a))
    for old_index, new_index in enumerate(permutation):
        shuffled_a[new_index] = a[old_index]
        shuffled_b[new_index] = b[old_index]
    return shuffled_a, shuffled_b
# x,y = shuffle_in_unison(x, y)

In [5]:
# import required module
import os
# assign directory
directory = '../data/GLEAM'
 
# iterate over files in
# that directory
files_name = []
for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        files_name.append(f)
        # print(f)

#### No Interpolation

In [6]:
# weeks_1_df = pd.DataFrame()
# weeks_2_df = pd.DataFrame()
# weeks_3_df = pd.DataFrame()
# weeks_4_df = pd.DataFrame()
# for i in files_name:
#     if i.endswith(".csv"):
#         df = pd.read_csv(i)
#         # if df['target'] == '1 wk ahead inc flu hosp':
#         weeks_1_df = weeks_1_df.append(df[(df['target'] == '1 wk ahead inc flu hosp') & (df['type'] == 'point')])
#         weeks_2_df = weeks_2_df.append(df[(df['target'] == '2 wk ahead inc flu hosp') & (df['type'] == 'point')])
#         weeks_3_df = weeks_3_df.append(df[(df['target'] == '3 wk ahead inc flu hosp') & (df['type'] == 'point')])
#         weeks_4_df = weeks_4_df.append(df[(df['target'] == '4 wk ahead inc flu hosp') & (df['type'] == 'point')])

# weeks_1_df = weeks_1_df.drop(['target','type','quantile'],axis = 1)
# weeks_2_df = weeks_2_df.drop(['target','type','quantile'],axis = 1)
# weeks_3_df = weeks_3_df.drop(['target','type','quantile'],axis = 1)
# weeks_4_df = weeks_4_df.drop(['target','type','quantile'],axis = 1)


# weeks_1_df = weeks_1_df.sort_values(by=['target_end_date', 'location'])
# weeks_2_df = weeks_2_df.sort_values(by=['target_end_date', 'location'])
# weeks_3_df = weeks_3_df.sort_values(by=['target_end_date', 'location'])
# weeks_4_df = weeks_4_df.sort_values(by=['target_end_date', 'location'])


# # # weeks to drop
# # lst_weeks_drop = ['2022-06-11','2022-06-18', '2022-06-25','2022-07-02','2022-07-09','2022-07-16', '2022-10-22', '2022-10-29', '2022-11-05', '2022-11-12','2022-11-19','2022-11-26', '2022-12-03','2022-12-10']
# # # states to drop 
# states_to_drop = ['11','US']

# # weeks_1_df = weeks_1_df[~weeks_1_df['target_end_date'].isin(lst_weeks_drop)]
# # weeks_2_df = weeks_2_df[~weeks_2_df['target_end_date'].isin(lst_weeks_drop)]
# # weeks_3_df = weeks_3_df[~weeks_3_df['target_end_date'].isin(lst_weeks_drop)]
# # weeks_4_df = weeks_4_df[~weeks_4_df['target_end_date'].isin(lst_weeks_drop)]

# weeks_1_df = weeks_1_df[~weeks_1_df['location'].isin(states_to_drop)]
# weeks_2_df = weeks_2_df[~weeks_2_df['location'].isin(states_to_drop)]
# weeks_3_df = weeks_3_df[~weeks_3_df['location'].isin(states_to_drop)]
# weeks_4_df = weeks_4_df[~weeks_4_df['location'].isin(states_to_drop)]


# # 1 week ahead
# week_1_df_2 = weeks_1_df.drop_duplicates(subset=['target_end_date'])
# week_1_df_3 = weeks_1_df.drop_duplicates(subset=['location'])
# list1_week1 = list(week_1_df_2['target_end_date'][3:])
# list2_week1 = list(week_1_df_3['location'])

# # 2 week ahead
# week_2_df_2 = weeks_2_df.drop_duplicates(subset=['target_end_date'])
# week_2_df_3 = weeks_2_df.drop_duplicates(subset=['location'])
# list1_week2 = list(week_2_df_2['target_end_date'][2:-1])
# list2_week2 = list(week_2_df_3['location'])

# # 3 week ahead
# week_3_df_2 = weeks_3_df.drop_duplicates(subset=['target_end_date'])
# week_3_df_3 = weeks_3_df.drop_duplicates(subset=['location'])
# list1_week3 = list(week_3_df_2['target_end_date'][1:-2])
# list2_week3 = list(week_3_df_3['location'])


# # 4 week ahead
# week_4_df_2 = weeks_4_df.drop_duplicates(subset=['target_end_date'])
# week_4_df_3 = weeks_4_df.drop_duplicates(subset=['location'])
# list1_week4 = list(week_4_df_2['target_end_date'][:-3])
# list2_week4 = list(week_4_df_3['location'])

# # Find comman weeks in GLEAM pred
# comman_weeks = sorted(list(set.intersection(*map(set, [list1_week1, list1_week2, list1_week3,list1_week4]))))

# time_length = len(comman_weeks)
# state_length = len(list2_week4)

#### Include Interpolation datasets

In [7]:
weeks_1_df = pd.DataFrame()
weeks_2_df = pd.DataFrame()
weeks_3_df = pd.DataFrame()
weeks_4_df = pd.DataFrame()
for i in files_name:
    if i.endswith(".csv"):
        df = pd.read_csv(i)
        # if df['target'] == '1 wk ahead inc flu hosp':
        weeks_1_df = weeks_1_df.append(df[(df['target'] == '1 wk ahead inc flu hosp') & (df['type'] == 'point')])
        weeks_2_df = weeks_2_df.append(df[(df['target'] == '2 wk ahead inc flu hosp') & (df['type'] == 'point')])
        weeks_3_df = weeks_3_df.append(df[(df['target'] == '3 wk ahead inc flu hosp') & (df['type'] == 'point')])
        weeks_4_df = weeks_4_df.append(df[(df['target'] == '4 wk ahead inc flu hosp') & (df['type'] == 'point')])

weeks_1_df = weeks_1_df.drop(['target','type','quantile'],axis = 1)
weeks_2_df = weeks_2_df.drop(['target','type','quantile'],axis = 1)
weeks_3_df = weeks_3_df.drop(['target','type','quantile'],axis = 1)
weeks_4_df = weeks_4_df.drop(['target','type','quantile'],axis = 1)


weeks_1_df = weeks_1_df.sort_values(by=['target_end_date', 'location'])
weeks_2_df = weeks_2_df.sort_values(by=['target_end_date', 'location'])
weeks_3_df = weeks_3_df.sort_values(by=['target_end_date', 'location'])
weeks_4_df = weeks_4_df.sort_values(by=['target_end_date', 'location'])

week1_after_interpolation = pd.read_csv('../data/Flu_Interpolation/week1_after_interpolation.csv')
week2_after_interpolation = pd.read_csv('../data/Flu_Interpolation/week2_after_interpolation.csv')
week3_after_interpolation = pd.read_csv('../data/Flu_Interpolation/week3_after_interpolation.csv')
week4_after_interpolation = pd.read_csv('../data/Flu_Interpolation/week4_after_interpolation.csv')

week1_after_interpolation.rename(columns = {"value_a": "value"}, inplace = True)
week2_after_interpolation.rename(columns = {"value_a": "value"}, inplace = True)
week3_after_interpolation.rename(columns = {"value_a": "value"}, inplace = True)
week4_after_interpolation.rename(columns = {"value_a": "value"}, inplace = True)

temp_merged_week1_df = pd.merge(weeks_1_df, week1_after_interpolation, on=['target_end_date', 'location'], how="outer", validate="one_to_many")[['target_end_date', 'location', 'value_x','value_y']]
temp_merged_week1_df['value_x'] = temp_merged_week1_df['value_x'].fillna(temp_merged_week1_df['value_y'])
weeks_1_df = temp_merged_week1_df.rename(columns = {"value_x": "value"}).sort_values(by=['target_end_date', 'location'])[['target_end_date', 'location', 'value']]

temp_merged_week2_df = pd.merge(weeks_2_df, week2_after_interpolation, on=['target_end_date', 'location'], how="outer", validate="one_to_many")[['target_end_date', 'location', 'value_x','value_y']]
temp_merged_week2_df['value_x'] = temp_merged_week2_df['value_x'].fillna(temp_merged_week2_df['value_y'])
weeks_2_df = temp_merged_week2_df.rename(columns = {"value_x": "value"}).sort_values(by=['target_end_date', 'location'])[['target_end_date', 'location', 'value']]

temp_merged_week3_df = pd.merge(weeks_3_df, week3_after_interpolation, on=['target_end_date', 'location'], how="outer", validate="one_to_many")[['target_end_date', 'location', 'value_x','value_y']]
temp_merged_week3_df['value_x'] = temp_merged_week3_df['value_x'].fillna(temp_merged_week3_df['value_y'])
weeks_3_df = temp_merged_week3_df.rename(columns = {"value_x": "value"}).sort_values(by=['target_end_date', 'location'])[['target_end_date', 'location', 'value']]

temp_merged_week4_df = pd.merge(weeks_4_df, week4_after_interpolation, on=['target_end_date', 'location'], how="outer", validate="one_to_many")[['target_end_date', 'location', 'value_x','value_y']]
temp_merged_week4_df['value_x'] = temp_merged_week4_df['value_x'].fillna(temp_merged_week4_df['value_y'])
weeks_4_df = temp_merged_week4_df.rename(columns = {"value_x": "value"}).sort_values(by=['target_end_date', 'location'])[['target_end_date', 'location', 'value']]


# # weeks to drop
# lst_weeks_drop = ['2022-06-11','2022-06-18', '2022-06-25','2022-07-02','2022-07-09','2022-07-16', '2022-10-22', '2022-10-29', '2022-11-05', '2022-11-12','2022-11-19','2022-11-26', '2022-12-03','2022-12-10']
# # states to drop 
states_to_drop = ['11','US']

# weeks_1_df = weeks_1_df[~weeks_1_df['target_end_date'].isin(lst_weeks_drop)]
# weeks_2_df = weeks_2_df[~weeks_2_df['target_end_date'].isin(lst_weeks_drop)]
# weeks_3_df = weeks_3_df[~weeks_3_df['target_end_date'].isin(lst_weeks_drop)]
# weeks_4_df = weeks_4_df[~weeks_4_df['target_end_date'].isin(lst_weeks_drop)]

weeks_1_df = weeks_1_df[~weeks_1_df['location'].isin(states_to_drop)]
weeks_2_df = weeks_2_df[~weeks_2_df['location'].isin(states_to_drop)]
weeks_3_df = weeks_3_df[~weeks_3_df['location'].isin(states_to_drop)]
weeks_4_df = weeks_4_df[~weeks_4_df['location'].isin(states_to_drop)]


# 1 week ahead
week_1_df_2 = weeks_1_df.drop_duplicates(subset=['target_end_date'])
week_1_df_3 = weeks_1_df.drop_duplicates(subset=['location'])
list1_week1 = list(week_1_df_2['target_end_date'][3:])
list2_week1 = list(week_1_df_3['location'])

# 2 week ahead
week_2_df_2 = weeks_2_df.drop_duplicates(subset=['target_end_date'])
week_2_df_3 = weeks_2_df.drop_duplicates(subset=['location'])
list1_week2 = list(week_2_df_2['target_end_date'][2:-1])
list2_week2 = list(week_2_df_3['location'])

# 3 week ahead
week_3_df_2 = weeks_3_df.drop_duplicates(subset=['target_end_date'])
week_3_df_3 = weeks_3_df.drop_duplicates(subset=['location'])
list1_week3 = list(week_3_df_2['target_end_date'][1:-2])
list2_week3 = list(week_3_df_3['location'])


# 4 week ahead
week_4_df_2 = weeks_4_df.drop_duplicates(subset=['target_end_date'])
week_4_df_3 = weeks_4_df.drop_duplicates(subset=['location'])
list1_week4 = list(week_4_df_2['target_end_date'][:-3])
list2_week4 = list(week_4_df_3['location'])

# Find comman weeks in GLEAM pred
comman_weeks = sorted(list(set.intersection(*map(set, [list1_week1, list1_week2, list1_week3,list1_week4]))))

time_length = len(comman_weeks)
state_length = len(list2_week4)

#### ground truth for flu

In [8]:
# weeks to drop
# lst_weeks_drop = lst_weeks_drop = ['2022-06-11','2022-06-18', '2022-06-25','2022-07-02','2022-07-09',\
#     '2022-07-16', '2022-10-22', '2022-10-29', '2022-11-05', '2022-11-12','2022-11-19','2022-11-26', '2022-12-03','2022-12-10']
# states to drop 
states_to_drop = ['11','US']

In [9]:
dfg = pd.read_csv('../data/CDC/truth-Incident Hospitalizations.csv')

In [10]:
dfg['date'] = pd.to_datetime(dfg['date'])

In [11]:
# dfg_date_filtered = dfg[dfg['date'] >= '2022-02-26']
dfg_date_filtered = dfg[(dfg['date'] >= '2022-02-26') & (dfg['date'] <= '2023-01-28')]
# dfg_date_filtered = dfg_date_filtered[dfg_date_filtered['date'].isin(comman_weeks)]
# dfg_date_filtered = dfg_date_filtered[~dfg_date_filtered['date'].isin(lst_weeks_drop)] # drop the weeks 
dfg_date_filtered = dfg_date_filtered[~dfg_date_filtered['location'].isin(states_to_drop)]
# only get the states that are in the prediction
dfg_date_filtered_temp = dfg_date_filtered[dfg_date_filtered['location'].isin(list2_week1)]
# # only get the dates that are in the prediction
# dfg_date_filtered_temp = dfg_date_filtered_temp[dfg_date_filtered_temp['date'].isin(list1_week4)]
# dfg_date_filtered_temp = dfg_date_filtered_temp.sort_values(by=['date', 'location'])
dfg_date_filtered_temp = dfg_date_filtered_temp.sort_values(by=['date', 'location'])

In [12]:
flu_groundtruth = np.resize(dfg_date_filtered_temp.groupby(['date','location']).sum().to_numpy().T, (time_length,state_length)) # 32,50
flu_groundtruth = flu_groundtruth.reshape(1,time_length,state_length)

#### Flu weekly prediction

#### Flu Prediction Matrix

In [13]:
pred_week1 = np.zeros([time_length,state_length])
no_value_1_week = {}
# for id1,i in enumerate(list1_week1):
for id1,i in enumerate(comman_weeks):
    df4 = weeks_1_df.loc[weeks_1_df['target_end_date'] == i]
    for id2,j in enumerate(list2_week1):
        df5 = df4.loc[df4['location'] == j]
        try:
            pred_week1[id1,id2] = df5['value']
        except:
            # print('error')
            if i not in no_value_1_week.keys():
                no_value_1_week[i] = [j]
            else:
                no_value_1_week[i].append(j)
print(pred_week1.shape)

(50, 50)


In [14]:
pred_week2 = np.zeros([time_length,state_length])
no_value_2_week = {}
# for id1,i in enumerate(list1_week2):
for id1,i in enumerate(comman_weeks):
    df4 = weeks_2_df.loc[weeks_2_df['target_end_date'] == i]
    for id2,j in enumerate(list2_week2):
        df5 = df4.loc[df4['location'] == j]
        try:
            pred_week2[id1,id2] = df5['value']
        except:
            # print('error')
            if i not in no_value_2_week.keys():
                no_value_2_week[i] = [j]
            else:
                no_value_2_week[i].append(j)
print(pred_week2.shape)

(50, 50)


In [15]:
pred_week3 = np.zeros([time_length,state_length])
no_value_3_week = {}
# for id1,i in enumerate(list1_week3):
for id1,i in enumerate(comman_weeks):
    df4 = weeks_3_df.loc[weeks_3_df['target_end_date'] == i]
    for id2,j in enumerate(list2_week3):
        df5 = df4.loc[df4['location'] == j]
        try:
            pred_week3[id1,id2] = df5['value']
        except:
            # print('error')
            if i not in no_value_3_week.keys():
                no_value_3_week[i] = [j]
            else:
                no_value_3_week[i].append(j)
print(pred_week3.shape)

(50, 50)


In [16]:
pred_week4 = np.zeros([time_length,state_length])
no_value_4_week = {}
# for id1,i in enumerate(list1_week4):
for id1,i in enumerate(comman_weeks):
    df4 = weeks_4_df.loc[weeks_4_df['target_end_date'] == i]
    for id2,j in enumerate(list2_week4):
        df5 = df4.loc[df4['location'] == j]
        try:
            pred_week4[id1,id2] = df5['value']
        except:
            # print('error')
            if i not in no_value_4_week.keys():
                no_value_4_week[i] = [j]
            else:
                no_value_4_week[i].append(j)
print(pred_week4.shape)

(50, 50)


In [22]:
flu_pred = np.stack([pred_week1,pred_week2,pred_week3,pred_week4],axis=0)
flu_pred.shape

(4, 50, 50)

#### Residuals

In [23]:
flu_residual = flu_pred - flu_groundtruth
residual_trans = flu_residual.transpose(1,2,0)
print(residual_trans.shape)

(50, 50, 4)


In [24]:
# x_offsets = np.sort(np.concatenate((np.arange(-6, 1, 1),)))
# print(x_offsets)
# y_offsets = np.array([7])
# print(y_offsets)

In [25]:
#x data

x_num_samples, x_num_nodes = time_length, state_length
x_data = residual_trans
# x_data = residual.transpose(1,2,0)

x_day = list(range(0,x_num_samples))

x_day = np.tile(x_day, [1, x_num_nodes, 1]).transpose((2, 1, 0))
x_data = np.concatenate([x_data,x_day], axis=-1)
print(x_data[:,:,4])

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 2.  2.  2. ...  2.  2.  2.]
 ...
 [47. 47. 47. ... 47. 47. 47.]
 [48. 48. 48. ... 48. 48. 48.]
 [49. 49. 49. ... 49. 49. 49.]]


In [26]:
x1 = np.stack(x_data, axis=0)[:time_length-4]
x1 = x1.reshape(time_length-4,1,state_length,5)

In [27]:
list5 = []
for i in range(time_length):
    residual_sum4 = np.sum((flu_residual[:,i:i+1]),axis=1)
    list5.append(residual_sum4)
residual_sum = np.stack(list5,axis =1)
residual_sum_trans = residual_sum.transpose(1,2,0)
print(residual_sum_trans.shape)

(50, 50, 4)


In [28]:
# y_data = np.stack([residual_trans[1:20,:,0],residual_trans[2:21,:,1],
#                         residual_trans[3:22,:,2],residual_trans[4:23,:,3]],axis=-1)
y_data = np.stack([residual_sum_trans[1:time_length-3,:,0],residual_sum_trans[2:time_length-2,:,1],
                        residual_sum_trans[3:time_length-1,:,2],residual_sum_trans[4:time_length,:,3]],axis=-1)
y1 = np.expand_dims(y_data,axis=1)
y1 = y1.transpose(0,3,2,1)
y_test = np.zeros([1,4,state_length,1])

print(y1.shape)
print(y_test.shape)

(46, 4, 50, 1)
(1, 4, 50, 1)


In [29]:
x_test = np.stack(x_data, axis=0)[-1].reshape(1,1,state_length,5)

#### No shuffle

In [30]:
# x1 = np.stack(x_data, axis=0)[:12]
# x1 = x1.reshape(12,1,50,5)

# y_data = np.stack([residual_trans[0:12,:,0],residual_trans[1:13,:,1],
#                         residual_trans[2:14,:,2],residual_trans[3:15,:,3]],axis=-1)
# y1 = np.expand_dims(y_data,axis=1)
# y1 = y1.transpose(0,3,2,1)

# without shuffling 
num_val = 12
num_train = 34
# num_test = 11

x_train, y_train = x1[:num_train], y1[:num_train]
x_val, y_val = x1[num_train:num_train+num_val], y1[num_train:num_train+num_val]
# x_test, y_test = x1[num_train+num_val:], y1[num_train+num_val:]

#### shuffle data

In [201]:

# x_shuffle, y_shuffle = shuffle_in_unison(x1, y1)

# # num_samples = x1.shape[0]
# # num_val = int(num_samples*0.5)
# # num_train = num_samples-num_val

# num_val = 10
# num_train = 11
# num_test = 1
# # train
# x_train, y_train = x_shuffle[:num_train], y_shuffle[:num_train]

# # val
# x_val, y_val = (
#     x_shuffle[num_train: num_train + num_val],
#     y_shuffle[num_train: num_train + num_val],
# )
# # x_test = x_shuffle[num_train+num_val:]
# # x_test, y_test = (x_shuffle[num_train+num_val:], y_shuffle[num_train+num_val:])

In [33]:
week_num = "week50"
for cat in ["train", "val", "test"]:
    _x, _y = locals()["x_" + cat], locals()["y_" + cat]
    print(cat, "x: ", _x.shape, "y:", _y.shape)
    np.savez_compressed(
        os.path.join("../data/shuffled_data/week50", "%s.npz" % cat),
        x=_x,
        y=_y
        # x_offsets=x_offsets.reshape(list(x_offsets.shape) + [1]),
        # y_offsets=y_offsets.reshape(list(y_offsets.shape) + [1]),
    )

train x:  (34, 1, 50, 5) y: (34, 4, 50, 1)
val x:  (12, 1, 50, 5) y: (12, 4, 50, 1)
test x:  (1, 1, 50, 5) y: (1, 4, 50, 1)


In [34]:
difference = np.absolute(y_test)
difference[difference != difference] = 0
mae = difference.mean()
mae

0.0