In [1]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
import pandas as pd
# with open('../data/sensor_graph/adj_mx.pkl', 'rb') as f:
#     states_data = pickle.load(f)

In [2]:
states_in_the_prediction = ['01','02','04','05','06','08','09','10','12','13','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40',
 '41','42','44','45','46','47','48','49','50','51','53','54','55','56']

In [7]:
test_data = np.load('../data/shuffled_data/week1/test.npz')

In [15]:
test_data['y'].shape

(2, 1, 1, 50)

In [3]:
npz = np.load("../data/Result_data/plotweek1result/seed7epo419.npz")
pred = npz['prediction']

In [34]:
pred

array([[[[-2.54576492e+01,  4.86760216e+01,  4.62916779e+02],
         [-2.96360550e+01,  1.25181580e+00,  6.80119202e+02],
         [ 2.15031128e+01,  2.37197052e+02,  1.34734644e+03],
         [-9.88105774e+00,  1.14436752e+02,  1.31295264e+03],
         [ 2.40933380e+01,  2.14813400e+02,  1.29694946e+03],
         [ 3.11976013e+01,  2.49433868e+02,  1.39030090e+03],
         [ 1.97825241e+01,  2.16011230e+02,  1.32626550e+03],
         [ 6.62308502e+00,  1.49929092e+02,  8.00729370e+02],
         [ 3.13259735e+01,  2.50127777e+02,  1.38727625e+03],
         [ 8.02462769e+00,  2.02791809e+02,  1.14146033e+03],
         [-1.52990723e+00,  1.38096893e+02,  1.21441162e+03],
         [-6.09418488e+00,  9.42510529e+01,  5.58501648e+02],
         [ 7.20685577e+00,  1.30156113e+02,  1.24281409e+03],
         [-7.13974762e+00,  1.37499084e+02,  1.21668140e+03],
         [ 1.36619186e+01,  2.13782959e+02,  1.40679871e+03],
         [-8.63236237e+00,  1.02881996e+02,  1.34586646e+03],
        

In [23]:
npz['truth'][0][0]

array([ 41.999996 ,   3.       ,  48.       ,  30.       , 115.       ,
        30.       ,  32.       ,   5.0000076, 359.       ,  68.       ,
        11.000008 ,  17.       ,  61.       ,  66.       ,  45.       ,
        17.       ,  29.       ,  41.999996 ,  11.000008 ,  36.999996 ,
        71.       ,  86.       ,  15.000008 ,  30.       ,  68.       ,
        10.000008 ,  22.       ,  11.000008 ,  20.       ,  70.       ,
        17.       , 154.       ,  35.       ,  22.       ,  67.       ,
        96.       ,  10.000008 , 138.       ,  10.000008 ,  34.       ,
        16.       ,  37.999996 , 328.99997  ,   5.0000076,   6.0000076,
        53.       ,  56.       ,  19.       ,  44.       ,   5.0000076],
      dtype=float32)

In [27]:
pred[0][1][:,np.array([False, True, False,])].flatten()

array([  8.70652  ,   1.1995468, 227.5083   , 107.42997  , 208.37686  ,
       248.8548   , 199.41428  , 180.06001  , 251.1318   , 154.17976  ,
       138.10612  , 104.02958  , 134.01038  , 155.51735  , 215.67902  ,
        96.353714 , 158.13484  , 153.04034  , 192.289    , 153.87708  ,
       109.144325 , 186.91757  , 165.12117  ,  71.76641  ,  35.096085 ,
        76.6169   ,  49.870457 , 112.54471  ,  93.97165  ,  91.5535   ,
       193.16211  ,  18.420876 ,  47.724567 ,  -1.2434464,   3.5320053,
        25.62741  ,  81.15781  ,  27.640854 ,  65.636765 , 106.67502  ,
        40.17393  ,  38.058    ,  62.92732  ,  59.440563 ,  27.96199  ,
        44.793358 , 123.63316  ,  39.143486 ,  38.62164  ,  26.125877 ],
      dtype=float32)

In [26]:
np.mean(np.abs(pred[0][1][:,np.array([False, True, False,])].flatten()) - npz['truth'][0][0])

50.544044

In [28]:
temp_week = np.array([ 58.,  10., 109.,  61., 198.,  33.,  31.,   5., 522.,  72.,   0.,
        30.,  62.,  96.,  43.,  41.,  30.,  70.,  31.,  61., 122., 154.,
        25.,  53.,  94.,  12.,  57.,  21.,  20., 102.,  30., 243.,  60.,
        28., 107., 139.,  25., 285.,  14.,  60.,  11.,  76., 454.,  17.,
        11.,  64.,  80.,  13.,  95.,  11.])

In [30]:
temp_week_1 = np.array([ 92.,   8., 139.,  97., 354.,  85.,  72.,  11., 625., 113.,   9.,
        42., 160., 151.,  87.,  49.,  62.,  89.,  53., 102., 238., 290.,
        48.,  47., 176.,  37.,  58.,  29.,  45., 157.,  43., 423., 129.,
        48., 184., 268.,  62., 427.,  10.,  78.,  16.,  88., 705.,  27.,
        10., 109., 133.,  36., 163.,  16.])

In [29]:
np.mean(np.abs(pred[0][1][:,np.array([False, True, False,])].flatten()) - temp_week)

22.124044647216795

In [33]:
np.mean(np.abs(pred[0][0][:,np.array([False, True, False,])].flatten()) - temp_week_1)

-3.267140884399414